# Generated by Django 4.0.6 on 2022-07-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
