# Generated by Django 4.0.6 on 2022-07-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_social_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='home_text',
            field=models.TextField(),
        ),
    ]
