# Generated by Django 4.0.6 on 2022-07-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_github_alter_project_medium_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Art',
        ),
        migrations.AddField(
            model_name='home',
            name='linkedin',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
