# Generated by Django 4.0.6 on 2022-07-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_newsletter_delete_art_home_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='heading',
            field=models.TextField(),
        ),
    ]
