# Generated by Django 4.0.6 on 2022-07-24 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_newsletter_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='social',
            name='email',
        ),
        migrations.AddField(
            model_name='home',
            name='email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social',
            name='linkedin',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
