# Generated by Django 4.0.6 on 2022-07-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_project_image_project_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_link',
            field=models.URLField(),
        ),
    ]
